import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Gorrion Summer Camp 2022 - recruitment task</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Skończone! ;)</h1>

        <p className={styles.description}>
          <Link href={"/users"}>
            <span style={{ textDecoration: "underline", cursor: "pointer" }}>
              Przejdź do strony użytkowników
            </span>
          </Link>
        </p>
      </main>
    </div>
  );
};

export default Home;
