import { NextPage } from 'next';
import Head from 'next/head';
import { User } from '../lib/users';
import Layout from '../components/Layout/Layout';
import UserCard from '../components/UserCard/UserCard';
import classes from '../components/Layout/Layout.module.css';
import { getAllUsers } from '../lib/users';
import { Key } from 'react';

const Users: NextPage = (props: any) => {
  return (
    <Layout>
      <Head>
        <title>Gorrion Summer Camp 2022 - Frontend</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <ul className={classes.userlist}>
        {props.allUsers.map((value: User, index: Key): any => {
          return (
            <li key={index as Key}>
              <UserCard user={value} />
            </li>
          );
        })}
      </ul>
    </Layout>
  );
};

export async function getStaticProps() {
  const allUsers = await getAllUsers();

  return {
    props: { allUsers }, // will be passed to the page component as props
  };
}

export default Users;
